title: My data science route
author: Rakiya Emmanuel
email: rakiyaemmannuel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  finding a route to being a data scientist can be so engaging and tiring
I am hoping that my story will help someone find a start
 It will also point you to great resources

# social links
twitter_username: farukiya07
github_username:  farukiya

show_excerpts: true # set to false to remove excerpts on the homepage
